ADH-8 OOZIE-2396 Fix startup issue
the destination path for sharelib is: /user/oozie/share/lib/lib_20170626092357
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/commons/io/Charsets
	at org.apache.hadoop.security.Credentials.<clinit>(Credentials.java:222)
	at org.apache.hadoop.mapred.JobConf.<init>(JobConf.java:334)
	at org.apache.oozie.service.HadoopAccessorService.createJobConf(HadoopAccessorService.java:349)
	at org.apache.oozie.tools.OozieSharelibCLI.run(OozieSharelibCLI.java:171)
	at org.apache.oozie.tools.OozieSharelibCLI.main(OozieSharelibCLI.java:67)
Caused by: java.lang.ClassNotFoundException: org.apache.commons.io.Charsets