Disable orca in configure for gpdb
It looks like orca is enabled now by default. That is the cause
of following errro in beta5:

checking for gpos/_api.h... no
configure: error: GPOS header files are required for Pivotal Query Optimizer (orca)
error: Bad exit status from /var/tmp/rpm-tmp.dKMHSy (%build)
    Bad exit status from /var/tmp/rpm-tmp.dKMHSy (%build)